# -*- coding: utf-8 -*-
"""Nearest ปรึกษาอาจารย์แก้เล่ม ก่อนปรึกษา run code ดึง excel ออกมาด้วยModel-3-Linear_interp_lag7_5-models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16S9uCAwHbVfJipasJVOk3Vc5rb5QT1D9

| ขั้นตอน | รายละเอียด                                     |
| ------- | ---------------------------------------------- |
| 1       | รวบรวมหุ้นหลายตัว (AAPL, MSFT, TSLA, …)        |
| 2       | ตรวจวันหยุดตลาด + Interpolation (3 วิธี)       |
| 3       | สร้าง features (Lag7, SMA, EMA, BB, RSI, MACD) |
| 4       | Scaling train เท่านั้น                         |
| 5       | ใช้ TimeSeriesSplit หรือ Sliding 70/15/15      |
| 6       | Train หลายโมเดล (Linear, XGB, LSTM, Prophet)   |
| 7       | เก็บ RMSE, R² ลง DataFrame                     |
| 8       | สรุปเปรียบเทียบผลลัพธ์                         |
"""

!pip install pandas_market_calendars
!pip install yfinance scikit-learn xgboost matplotlib
import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import pandas_market_calendars as mcal
import matplotlib.pyplot as plt

# ไลบรารีสำหรับ Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.preprocessing import StandardScaler

# ------------------------------
# 0. กำหนด list หุ้นทั้งหมด
# ------------------------------
tickers = ["AAPL", "AMD", "AVGO", "GOOG", "GOOGL", "META", "MSFT", "NVDA"]

# กำหนดช่วงวันที่
start_date = datetime(2019, 1, 1)
end_date   = datetime(2024, 12, 31)

all_data_list = []

# ------------------------------
# 1. ดาวน์โหลดข้อมูลหุ้นทั้งหมด
# ------------------------------
for ticker in tickers:
    print(f"📥 Downloading {ticker} ...")
    data = yf.download(ticker, start=start_date.strftime('%Y-%m-%d'), end=end_date.strftime('%Y-%m-%d'))

    if data.empty:
        print(f"❌ No data for {ticker}")
        continue

    data.reset_index(inplace=True)

    if isinstance(data.columns, pd.MultiIndex):
        data.columns = [' '.join(col).strip() if isinstance(col, tuple) else col for col in data.columns.values]

    def clean_columns(cols):
        cleaned = []
        for col in cols:
            if 'Date' in col:
                cleaned.append('Date')
            else:
                cleaned.append(col.split()[0])
        return cleaned

    data.columns = clean_columns(data.columns)
    data['Symbol'] = ticker.upper()

    # Make sure 'Volume' column is included correctly
    wanted_cols = ['Date', 'Open','High','Low','Close', 'Volume', 'Symbol']
    data = data[[col for col in wanted_cols if col in data.columns]]

    all_data_list.append(data)

# Concatenate all dataframes in the list into a single dataframe
flat_df = pd.concat(all_data_list, ignore_index=True)

flat_df

# ----------------------------------------------
# 2. Descriptive Statistics ของหุ้นแต่ละตัว (รวม OHLC และ Volume)
# ----------------------------------------------

# 1. จัดกลุ่มด้วย 'Symbol' และคำนวณสถิติของคอลัมน์ที่ต้องการทั้งหมด
# Open, High, Low, Close, Volume
descriptive_stats = flat_df.groupby('Symbol')[['Open', 'High', 'Low', 'Close', 'Volume']].describe()

# 2. กำหนดกฎการปัดเศษสำหรับคอลัมน์ราคาและปริมาณการซื้อขาย
rounding_rules = {
    'Open': 2,
    'High': 2,
    'Low': 2,
    'Close': 2,
    'Volume': 0 # ปริมาณการซื้อขาย (Volume) ปัดเป็นจำนวนเต็ม
}

# 3. จัดรูปแบบการแสดงผลโดยใช้กฎการปัดเศษที่กำหนด
for col, decimals in rounding_rules.items():
    # ตรวจสอบว่าคอลัมน์หลัก (เช่น 'Open') มีอยู่ใน MultiIndex level 0 หรือไม่
    if col in descriptive_stats.columns.get_level_values(0):
        # ปัดเศษสถิติทั้งหมด (count, mean, std, min, 25%, 50%, 75%, max) ภายใต้คอลัมน์ราคานั้น ๆ
        descriptive_stats.loc[:, col] = descriptive_stats[col].round(decimals)

print("--- Descriptive Statistics of OHLCV (แยกตาม Symbol) ---")
print(descriptive_stats)

import pandas as pd
import pandas_market_calendars as mcal

# 1. สร้าง continuous date range
all_dates = pd.DataFrame({'Date': pd.date_range(flat_df['Date'].min(), flat_df['Date'].max())})

# 2. ขยาย Symbol list ให้ครบทุกวัน
symbols = flat_df['Symbol'].unique()
expanded_list = []
for sym in symbols:
    temp = all_dates.copy()
    temp['Symbol'] = sym
    expanded_list.append(temp)
all_dates_symbols = pd.concat(expanded_list, ignore_index=True)

# 3. merge กับ flat_df ของราคาหุ้น
full_df = all_dates_symbols.merge(flat_df, on=['Date','Symbol'], how='left')

# 4. สร้าง holiday / weekend
nyse = mcal.get_calendar('NYSE')
schedule = nyse.schedule(start_date=full_df['Date'].min(), end_date=full_df['Date'].max())
business_days = schedule.index.normalize()
business_set = set(business_days)

full_df['holiday'] = (~full_df['Date'].isin(business_set)).astype(int)
full_df['weekend'] = full_df['Date'].dt.dayofweek.isin([5,6]).astype(int)

# 5. pre_holiday / post_holiday
def compute_pre_holiday(date):
    return int((date + pd.Timedelta(days=1)) not in business_set)

def compute_post_holiday(date):
    return int((date - pd.Timedelta(days=1)) not in business_set)

full_df['pre_holiday'] = full_df['Date'].apply(compute_pre_holiday)
full_df['post_holiday'] = full_df['Date'].apply(compute_post_holiday)

# 6. ตรวจสอบ
print(full_df[['Date','Symbol','Close']].head(30))

# ----------------------------
# 1) เติมค่าว่าง Close ด้วย nearest
# ----------------------------
price_cols = ['Close']
for col in price_cols:
    full_df[col] = full_df.groupby('Symbol')[col].transform(
        lambda x: x.interpolate(method='nearest')
    )

flat_df=full_df.copy()

flat_df

full_df=flat_df

# ----------------------------
# 2) สร้าง lag 7 วันสำหรับ Close
# ----------------------------
lag_cols = []
for lag in range(1, 8):  # 1 ถึง 7 วัน
    col_name = f'Close_lag{lag}'
    full_df[col_name] = full_df.groupby('Symbol')['Close'].shift(lag)
    lag_cols.append(col_name)

print("จำนวน NaN ที่เหลือในแต่ละคอลัมน์:")
print(full_df[['Close','Open'] + lag_cols].isna().sum())

# แสดงตัวอย่าง
cols_to_show = ['Date','Symbol','Close'] + lag_cols
print(full_df[cols_to_show].head(15))

# 9. สร้าง Target: Close ของวันถัดไป
full_df['Close_next'] = full_df.groupby('Symbol')['Close'].shift(-1)

# 10. สร้าง Feature Matrix X
lag_cols = [f'Close_lag{i}' for i in range(1,8)]  # Close_lag1 ... Close_lag7

X_cols = lag_cols
X = full_df[X_cols]
# Target
y = full_df['Close_next']

# ตรวจสอบตัวอย่าง
print("Feature Matrix X:")
print(X.head(10))
print("\nTarget y:")
print(y.head(10))

# 11. ลบ row ที่มี NaN ใน X หรือ y
data_ml = pd.concat([X, y], axis=1)  # รวม X และ y ชั่วคราว
data_ml_clean = data_ml.dropna().reset_index(drop=True)

# แยกกลับเป็น X และ y
X_clean = data_ml_clean[X_cols]
y_clean = data_ml_clean['Close_next']

# ตรวจสอบตัวอย่าง
print("Feature Matrix X (clean):")
print(X_clean.head(10))
print("\nTarget y (clean):")
print(y_clean.head(10))

from sklearn.preprocessing import StandardScaler

# 1. สร้าง scaler
scaler = StandardScaler()

# 2. fit & transform X_clean
X_scaled = scaler.fit_transform(X_clean)

# 3. ตรวจสอบตัวอย่าง
import pandas as pd
X_scaled_df = pd.DataFrame(X_scaled, columns=X_cols)
print(X_scaled_df.head(10))

from tqdm import tqdm

# สร้าง DataFrame เก็บข้อมูลทุก window พร้อมวันที่จริง
window_details = []

window_train = 0.7
window_test = 0.15

for sym in tqdm(symbols, desc="Exporting sliding windows"):
    df_sym = full_df[flat_df['Symbol'] == sym].sort_values('Date').reset_index(drop=True)

    data_ml = df_sym[['Date'] + X_cols + ['Close_next']].dropna().reset_index(drop=True)

    n = len(data_ml)
    step = int(n * window_test)
    start = 0
    window_id = 1

    while start + int(n * window_train) + step <= n:
        train_idx = range(start, start + int(n * window_train))
        test_idx  = range(start + int(n * window_train), start + int(n * window_train) + step)

        # Train/Test Data พร้อมวันที่
        train_df = data_ml.iloc[train_idx].copy()
        train_df['Symbol'] = sym
        train_df['Window'] = window_id
        train_df['Set'] = 'Train'

        test_df = data_ml.iloc[test_idx].copy()
        test_df['Symbol'] = sym
        test_df['Window'] = window_id
        test_df['Set'] = 'Test'

        window_details.append(pd.concat([train_df, test_df], axis=0))

        start += step
        window_id += 1

# เตรียมโมเดล
models = {
    'Linear': LinearRegression(),
    'RandomForest': RandomForestRegressor(n_estimators=100, random_state=42),
    'GradientBoosting': GradientBoostingRegressor(n_estimators=100, random_state=42),
    'XGBoost': XGBRegressor(n_estimators=100, random_state=42, verbosity=0),
    'SVR': SVR()
}

# ตัวแปรเก็บผลลัพธ์ทั้งหมด
all_results = []

# สมมติว่าเรา assign Model Name เอง
model_name = "Linearinterp_lag7_5 models"

# Loop แต่ละ Symbol
symbols = flat_df['Symbol'].unique()
lag_cols = [f'Close_lag{i}' for i in range(1, 8)]
X_cols = lag_cols

for sym in symbols:
    df_sym = flat_df[flat_df['Symbol'] == sym].sort_values('Date').reset_index(drop=True)

    # Feature & Target
    X = df_sym[X_cols]
    y = df_sym['Close_next']

    # ลบ NaN
    data_ml = pd.concat([X, y], axis=1).dropna().reset_index(drop=True)
    X_clean = data_ml[X_cols]
    y_clean = data_ml['Close_next']

    n = len(X_clean)
    step = int(n * window_test)
    start = 0

    # Sliding Window
    while start + int(n * window_train) + step <= n:
        train_idx = range(start, start + int(n*window_train))
        test_idx  = range(start + int(n*window_train), start + int(n*window_train) + step)

        X_train = X_clean.iloc[train_idx].values
        y_train = y_clean.iloc[train_idx].values
        X_test  = X_clean.iloc[test_idx].values
        y_test  = y_clean.iloc[test_idx].values

        # Scale Training set
        scaler = StandardScaler()
        X_train_scaled = scaler.fit_transform(X_train)
        X_test_scaled  = scaler.transform(X_test)

        # Train & Evaluate ทุกโมเดล
        for name, model in models.items():
            model.fit(X_train_scaled, y_train)
            y_pred = model.predict(X_test_scaled)

            all_results.append({
                'Symbol': sym,
                'model': name,
                'start_idx': start,
                'rmse': np.sqrt(mean_squared_error(y_test, y_pred)),
                'mae': mean_absolute_error(y_test, y_pred),
                'r2': r2_score(y_test, y_pred),
                'Model Name': model_name
            })

        start += step

# แปลงเป็น DataFrame
results_df = pd.DataFrame(all_results)

# รวมทั้งหมด
window_full_df = pd.concat(window_details, axis=0).reset_index(drop=True)

# จัดคอลัมน์ให้อ่านง่าย
cols_order = ['Symbol', 'Window', 'Set', 'Date'] + X_cols + ['Close_next']
window_full_df = window_full_df[cols_order]

# export เป็น Excel (ทุก symbol และทุก window)
excel_path = "sliding_window_full_details.xlsx"
window_full_df.to_excel(excel_path, index=False)
print(f"✅ บันทึกไฟล์รายละเอียด Sliding Window แล้ว: {excel_path}")

# ถ้าอยากได้สรุปเฉพาะช่วงวันที่ของแต่ละ window (start-end)
summary_records = []
for (sym, window), group in window_full_df.groupby(['Symbol', 'Window']):
    train_group = group[group['Set'] == 'Train']
    test_group = group[group['Set'] == 'Test']
    summary_records.append({
        'Symbol': sym,
        'Window': window,
        'Train_Start': train_group['Date'].iloc[0],
        'Train_End': train_group['Date'].iloc[-1],
        'Test_Start': test_group['Date'].iloc[0],
        'Test_End': test_group['Date'].iloc[-1],
        'Train_Size': len(train_group),
        'Test_Size': len(test_group)
    })

summary_df = pd.DataFrame(summary_records)
summary_df.to_excel("sliding_window_summary.xlsx", index=False)
print("✅ บันทึกไฟล์สรุปช่วงวันที่แต่ละ window แล้ว: sliding_window_summary.xlsx")

summary_df

# Export to Excel
results_df.to_excel("results_output.xlsx", index=False)
print("✅ Exported results to results_output.xlsx")

results_df